### ISSUE TITLE
PHP exec() calls for update does not guard against injection

### ISSUE THREAD

**Issue by majiru** [KCCCDC/PowerHMI#1]
Her we can see there is a free form update box, and if you look int the php code you can see that it just uses an everyday exec() call to get the data.  With the right crafted input one can easily do some scary stuff.
![9rw07wf](https://cloud.githubusercontent.com/assets/3579600/12572140/e8db0eca-c3ad-11e5-8612-ca7e4abe02c9.jpg)

The code being put in here is:

 `;touch badThing.php; echo "<?php print('Look at all the things I can do!') ?>" > badThing.php`

and once the update button is clicked we can immediately see the outcome here:
![b6xaz5j](https://cloud.githubusercontent.com/assets/3579600/12572187/5efccc2e-c3ae-11e5-971e-ebdd0e62aba4.png)

**Comment by majiru** [comment]
Should be fixed with this commit: 806b07703247ce20cfd21334ff4b62362fbb5d5c.

**Comment by twstagg** [comment]
Nice job

**Comment by twstagg** [comment]
On top of the existing numeric check, we should also implement `escapeshellarg()`.
